pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build & Tag') {
            steps {

                 sh 'docker build -t kanban-dashboard:${BUILD_NUMBER} .'
                }
            }
        }

    }
}
