pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build & Tag') {
            steps {
                script {
                    env.IMAGE_TAG = "${env.BUILD_NUMBER}"

                    sh """
                        docker build -t kanban-dashboard:${IMAGE_TAG} .
                    """
                }
            }
        }

    }
}
