
environment {
    AWS_REGION = 'ap-south-1'
    ECR_REPO = 'your-ecr-repository'
    AWS_ACCOUNT_ID = 'your-aws-account-id'
    REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
}

stages {
    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build') {
        steps {
            sh '''
                pwd
                ls -la
                find . -name Dockerfile -type f
            '''
        }
    }

    stage('Login to ECR') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'registry-creds']]) {
                sh '''
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
                '''
            }
        }
    }

    stage('Push to ECR') {
        steps {
            sh '''
                docker tag ${ECR_REPO}:latest ${REGISTRY}/${ECR_REPO}:latest
                docker push ${REGISTRY}/${ECR_REPO}:latest
            '''
        }
    }
}
